Adding a contributing guide
icecube/pisa pull request #826
Opened 2024-09-16 14:31 UTC by JanWeldert

First draft of a contributing guide. Still needs some fine tuning, but that would be my idea of the overall structure.

_Not sure why the PR is showing some old commits, only the last one is important here_

2024-09-17 09:05 UTC, JanWeldert commented
Closes #825

2024-09-18 09:24 UTC, thehrh requested changes
see inline comments

2024-09-18 09:24 UTC, thehrh commented on docs/CONTRIBUTING.md
> +Found a bug or missing a functionality? Don't be afraid to tackle this! If you don't do it, maybe no one will.
"missing a feature" sounds more idiomatic to me here

2024-09-18 09:24 UTC, thehrh commented on docs/CONTRIBUTING.md
> +In any case, it is a good first step to document what you've found (or what's missing) in a GitHub issue. [Here](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue) is
* remove contractions here for consistency: you have, what is
* how to do it

2024-09-18 09:24 UTC, thehrh commented on docs/CONTRIBUTING.md
> +If you want to work on something already documented, you are more than welcome! But remember, the best way to close an issue is with a pull request.
* straight to the point: "You are more than welcome to ..."

2024-09-18 09:24 UTC, thehrh commented on docs/CONTRIBUTING.md
> +Once you implemented your changes, you can start a PR. You can start this early, even when you are still working on your code, to get feedback and let people know what you are working on. Use your ow
* I think it's fine to suggest to use own fork _and_ dedicated branch
* how to do it

2024-09-18 09:24 UTC, thehrh commented on docs/CONTRIBUTING.md
> +Everyone can (and should) review and merge PRs opened by other contributors. You can also just review and wait for others to merge, if you are unsure about the proposed changes.
We have no instructions on how to best merge a PR currently. For example, this PR has a number of unnecessary commits, which we should be able to get rid of with a squash merge. Maybe refrain from explicitly suggesting that everyone should perform merges for now (likely that only org members are able to do so anyway).

2024-09-18 09:24 UTC, thehrh commented on docs/CONTRIBUTING.md
> +If you are stuck with you code or have some generel questions, feel free to ask other people on slack (e.g. in the pisa-help channel).
* you -> your, generel -> general
* some comment that acknowledges that this repo is public while the slack channel you're referring to isn't?

2024-09-20 11:38 UTC, thehrh approved these changes

2024-09-20 11:41 UTC, merged